apiVersion: apps/v1
kind: Deployment
metadata:
  name: interface-frontend
  namespace: default
  labels:
    env: dev
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: interface-frontend
  template:
    metadata:
      labels:
        app: interface-frontend
    spec:
      containers:
        - name: interface-frontend
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "2"

