apiVersion: apps/v1
kind: Deployment
metadata:
  name: interface-frontend
  namespace: default
  labels:
    env: dev
spec: 
  selector:
    matchLabels:
      app: interface-frontend
  template:
    metadata:
      labels:
        app: interface-frontend
  containers:
    - name: interface-frontend
      image: 480936841767.dkr.ecr.ap-northeast-2.amazonaws.com/interface-app:frontend-${IMAGE_TAG}
