apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patchesStrategicMerge:
- frontend-deployment-patch.yaml
- frontend-service-patch.yaml
images:
- name: 480936841767.dkr.ecr.ap-northeast-2.amazonaws.com/frontend-app
  newName: 480936841767.dkr.ecr.ap-northeast-2.amazonaws.com/frontend-app
  newTag: frontend-20230801071519-9129e072
- name: 480936841767.dkr.ecr.ap-northeast-2.amazonaws.com/frontend-app:frontend-808300ad
  newName: 480936841767.dkr.ecr.ap-northeast-2.amazonaws.com/frontend-app:frontend-808300ad
- name: 480936841767.dkr.ecr.ap-northeast-2.amazonaws.com/order-app
  newName: 480936841767.dkr.ecr.ap-northeast-2.amazonaws.com/order-app
  newTag: order-20230801071519-9129e072
- name: 480936841767.dkr.ecr.ap-northeast-2.amazonaws.com/store-app
  newName: 480936841767.dkr.ecr.ap-northeast-2.amazonaws.com/store-app
  newTag: store-20230801071519-9129e072
- name: 480936841767.dkr.ecr.ap-northeast-2.amazonaws.com/user-app
  newName: 480936841767.dkr.ecr.ap-northeast-2.amazonaws.com/user-app
  newTag: user-20230801071519-9129e072
