apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: 
- ../../base
patchesStrategicMerge:
- frontend-deployment-patch.yaml
- frontend-service-patch.yaml
images:
- name: 480936841767.dkr.ecr.ap-northeast-2.amazonaws.com/frontend-app:frontend-808300ad
  newName: 480936841767.dkr.ecr.ap-northeast-2.amazonaws.com/frontend-app:frontend-808300ad