apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/interface-app
  newName: ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/interface-app
  newTag: frontend-${IMAGE_TAG}
resources:
- ../../base
patchesStrategicMerge:
- frontend-deployment-patch.yaml
- frontend-service-patch.yaml