apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/interface-app
  newName: ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/interface-app
  newTag: frontend-${IMAGE_TAG}
- name: 480936841767.dkr.ecr.ap-northeast-2.amazonaws.com/frontend-app
  newName: 480936841767.dkr.ecr.ap-northeast-2.amazonaws.com/frontend-app
  newTag: frontend-20230731204531-01a1d74b
- name: 480936841767.dkr.ecr.ap-northeast-2.amazonaws.com/order-app
  newName: 480936841767.dkr.ecr.ap-northeast-2.amazonaws.com/order-app
  newTag: order-20230731204532-01a1d74b
- name: 480936841767.dkr.ecr.ap-northeast-2.amazonaws.com/store-app
  newName: 480936841767.dkr.ecr.ap-northeast-2.amazonaws.com/store-app
  newTag: store-20230731204532-01a1d74b
- name: 480936841767.dkr.ecr.ap-northeast-2.amazonaws.com/user-app
  newName: 480936841767.dkr.ecr.ap-northeast-2.amazonaws.com/user-app
  newTag: user-20230731204532-01a1d74b
resources:
- ../../base
patchesStrategicMerge:
- frontend-deployment-patch.yaml
- frontend-service-patch.yaml
