apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/frontend-808300ad
  newName: ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/frontend-808300ad
  newTag: abcdefg
resources:
- ../../base/frontend-deployment.yaml
- ../../base/frontend-service.yaml
patches:
- target:
    kind: Deployment
    name: frontend
  path: frontend-deployment-patch.yaml
- target:
    kind: Service
    name: frontend
  path: frontend-service-patch.yaml
